#!/bin/sh

. ./init_test

echo "*** Test file size change while NNFS is running"

runA -f $H/A
runB -a $H/B

echo "AAAAAAAAAA" > $H/A/afile1
echo "BBBBBBBBBB" > $H/A/afile2
echo "CCCCCCCCCC" > $H/A/afile3
echo "DDDDDDDDDD" > $H/A/afile4
echo "EEEEEEEEEE" > $H/A/afile5
echo "FFFFFFFFFF" > $H/A/afile6

echo "AAAAAAAAAA" > $H/A/bfile1
echo "BBBBBBBBBB" > $H/A/bfile2
echo "CCCCCCCCCC" > $H/A/bfile3
echo "DDDDDDDDDD" > $H/A/bfile4
echo "EEEEEEEEEE" > $H/A/bfile5
echo "FFFFFFFFFF" > $H/A/bfile6

runA
runB

chmod 700   $H/B/afile2
echo "Y" >> $H/B/afile1
chmod 700   $H/B/afile4
echo "Z" >> $H/B/afile3
runB --exec_after_merge `pwd`/test54chmod
runA
runB
runA

same $H/A afile1 $H/B afile1 || Exit 7
same $H/A afile2 $H/B afile2 || Exit 8
same $H/A afile3 $H/B afile3 || Exit 9
same $H/A afile4 $H/B afile4 || Exit 10
same $H/A afile5 $H/B afile5 || Exit 11
same $H/A afile6 $H/B afile6 || Exit 12

Exit 0

