#!/bin/sh

. ./init_test

echo "*** Test file biggers than 4Gb"

runA -f $H/A
runB -a $H/B

cc -Wall bigfile.c
a.out >$H/A/bigfile
touch $H/A/f1

runA
runB

[ "$(ls -l $H/A/bigfile | sed 's/ [^ ]*$//')" != \
  "$(ls -l $H/B/bigfile | sed 's/ [^ ]*$//')" ] && Exit 1
same $H/A f1      $H/B f1      || Exit 2


Exit 0

