#!/bin/sh

. ./init_test

echo "*** Test if NNFS works with a bad history directory"

if [ $(id -u) = 0 ]
then
exit 0
fi

runA -f $H/A
runB -a $H/B

echo "AAAAAAAAAA" > $H/A/f

runA
runB

ln -s /usr/nonexistentdir $H/B/.nnfs/history
echo "HISTORIZE=yes" >>$H/B/.nnfs/nnfsrc

echo "BBBBBBBB" > $H/A/f

runA
runB

same $H/A f $H/B f || Exit 101

Exit 0
